# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 예쁜배경
email: placeless@outlook.com
author: "예쁜배경"
logo: "./apple-touch-icon.png"
lang: "ko"
description: "스마트폰 휴대폰 예쁜배경화면"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fluke103.github.io" # the base hostname & protocol for your site
timezone: Asia/Shanghai
encoding: UTF-8

social:
  name: placeless
  links:
    - https://twitter.com/placeless

webmaster_verifications:
  google: ""

tracking:
  ga_id: "UA-xxxxxx-yy"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

permalink: /blog/:title

